spring:
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: tictactoe.utils.GameRecordDeserializer
      properties:
        spring.json.trusted.packages: "*, tictactoe.dto, tictactoe.dto.*"
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: tictactoe.utils.GameRecordSerializer
      properties:
        spring.kafka.producer.properties.spring.json.type.mapping: gameRecord:tictactoe.dto.GameRecord,gameRecord:aggregation.dto.GameRecord
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: validate
  application:
    name: tictactoe-service
  flyway:
    baseline-on-migrate: 'true'
  datasource:
    password: root
    #username: postgres
    username: root
    url: jdbc:mysql://localhost:3306/social_gaming_platform_tictactoe_service?useSSL=false&createDatabaseIfNotExist=true
    #url: jdbc:postgresql://localhost:5432/social_gaming_platform_tictactoe_service?useSSL=false&createDatabaseIfNotExist=true

server:
  port: '8083'

#flyway:
#  locations: filesystem:db/migration
#  url: jdbc:mysql://localhost:3306/mysql
#  user: root
#  schemas: social_gaming_platform_tictactoe_service
#  password: root

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: true

platform:
  app:
    jwtSecret: tictactoeServiceSecretKey
    jwtExpiration: '86400000'