spring:
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: aggregation.util.GameRecordDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: aggregation.util.GameRecordSerializer
    streams:
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: aggregation.util.GameRecordSerde
        spring.json.trusted.packages: "*"
      state-dir: /tmp/kafka-streams/
  application:
    name: data-aggregation-service
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: 'true'
  datasource:
    password: root
    #username: postgres
    username: root
    url: jdbc:mysql://localhost:3306/social_gaming_platofrm_stats?useSSL=false&createDatabaseIfNotExist=true
    #url: jdbc:postgresql://localhost:5432/social_gaming_platofrm_stats?useSSL=false&createDatabaseIfNotExist=true

server:
  port: '8088'

eureka:
    client:
        service-url:
              defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true